### ISSUE TITLE
[PE-D][Tester B] Program fails to start again after exiting once

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-T17-3/tp#163] opened 2023-11-03 16:27 UTC
![Screenshot 2023-11-03 at 5.05.11 PM.png](https://raw.githubusercontent.com/ken-ruster/ped/main/files/f272690b-0f40-43bb-bad9-37ba84823a52.png)

After starting the program once, entering 2 drugs and 2 profiles, then not saving any of the information and quitting using the inbuilt bye command, subsequent attempts to start the program return an error where it fails to initialise.

Able to start the program normally once the files `users.txt` and `drugs.txt` are deleted, without the data.

As a result users may be unable to resume with their saved data when starting a new session.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: ken-ruster/ped#11

**Comment by TeoHaoZhi** [comment] 2023-11-04 14:59
response.accepetd - Hao Zhi

Duplicate of issue #171

**Closed by TeoHaoZhi** 2023-11-04 14:59 UTC
